### ISSUE TITLE
Rename. I can't understand that

### ISSUE THREAD

**Issue by expiredy** [AVollane/REVDataAPI#3]
https://github.com/AVollane/RXVBack/blob/409140e736bc870eac29c5e055bfd81dc37b5d34/RXVBack/Program.cs#L10 
So here we have an average developer's mistake, calling variables kinda unreadable, and in cause of that happens misunderstanding

**Comment by expiredy** [comment]
Good luck, average app calling variable  enjoyer

**Comment by AVollane** [comment]
Dear participant, I'm really sorry, but your issue was rejected. Thank you!

**Comment by expiredy** [comment]
Fuck you
